# Customer,Status summary URL,Alarm/Lost Connection URL

DC MyCompany,http://localhost:8080/dashboard/Teams%20Integration/data/STATUS_ID.json,http://localhost:8080/dashboard/Teams%20Integration/data/DETAIL_ID.json

# Server1 MyCompany,http://dbwatch2:8080/dashboard/Teams%20Integration/data/STATUS_ID.json,http://dbwatch2:8080/dashboard/Teams%20Integration/data/DETAIL_ID.json